application: m-codes
version: 2
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css

- url: /static
  static_dir: static
- url: /js
  static_dir: static/js
  
- url: /img
  static_dir: static/img

- url: /tmp
  static_dir: static/html

- url: .*
  script: main.py
